title: dukedotdev # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a game and web dev who enjoys coding in their free time. I'm still in High School, but I'm graduating this year, two years early!
  <br><br>
  I gained popularity in Rec Room contributing to a popular game, <a href="https://rec.net/room/Desert-Force-Military">^Desert-Force-Military</a>. After it was stolen from the original team, we went our seperate ways and moved on to different projects. I personally moved on to a passion project that is still very early in the works, under the organization <a href="https://github.com/MagiQuest">MQ-VR</a>.
  <br><br>
  <a href="https://rec.net/user/dukedotdev">View My Rec Room Profile</a>
  <br>
  <a href="https://steamcommunity.com/id/dukedotdev/">View My Steam Profile</a>
  <br>
  <a href="https://bsky.app/profile/dukedot.dev">View My Bluesky Profile</a>
  <br>
  <a href="https://github.com/dukedotdev">View My GitHub Profile</a>
  <br>
  <a href="https://discord.com/users/761738453670035518">View My Discord Profile</a>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
